2505-future/58hack-front

- lefthook.yml
- package.json
- pnpm-lock.yaml
Biome での lint check を、プッシュ前に行うようなツールを導入しました。
lint check を強制したいが、毎回コマンドを打つのは面倒だな～と思ったから
なし！
> chore: biome の lint check を pre-push 時に行うように設定

- .github/workflows/deploy-preview.yml
- PRが作成されるたびにpreviewを作成するワークフローを作成
- レビュー体験の向上
1. 〇〇の画面を開く
3. ...
> previewを作成するワークフローを作成

- app/routes/debug-components.tsx
- app/routes/waitingRoom.tsx
> CI/CD 止まってたので修正

- app/components/StartButton.tsx
- app/features/game/components/PhaserGame.tsx
- app/features/game/core/config/configLoader.ts
- app/features/game/core/objects/player.ts
- app/features/game/core/state/ClientGameStateManager.ts
- app/features/game/hooks/useClientGameState.ts
- app/routes/waiting.tsx
/waitingで待合室が起動するようにしました
/waitingにアクセスする
正確に仮面が出ていれば成功
1. 〇〇の画面を開く
3. ...
> /waitingで表示させるように

- app/api/createRoom.client.ts
- app/components/CreateRoomModal.tsx
- app/components/JoinRoomModal.tsx
- app/routes/auth.callback.tsx
- app/routes/home.tsx
> feat: 部屋作成APIの繋ぎ込み

- app/features/game/core/config/config.ts
- app/features/game/core/config/configLoader.ts
- app/features/game/core/objects/player.ts
- app/routes/waiting.tsx
- app/utils/genPoint.client.ts
> feat: 待機部屋を仮実装

- app/atoms/githubUser.ts
- app/root.tsx
- app/routes/waiting.tsx
> 部屋入室時に自分の GitHub データを送信するようにした

- app/api/joinRoom.client.ts
- app/components/CreateRoomModal.tsx
- app/components/JoinRoomModal.tsx
- app/features/game/core/config/configLoader.ts
- app/features/game/core/objects/player.ts
- app/features/game/core/state/ClientGameStateManager.ts
- app/routes/game.tsx
- app/routes/result.tsx
- app/routes/waiting.tsx
参加APIとの繋ぎこむ
参加ボタンから正しい合言葉を入力してokが返ってくる
> 参加APIとの繋ぎこみ

- app/api/getUsers.server.ts
- app/routes/waiting.tsx
> feat: 参加した時にすでにいるメンバーをフェッチする

- app/routes/waiting.tsx
> fix: すでに参加しているIDは登録しない

- app/components/Header.tsx
- app/routes/auth.login.tsx
レスポンシブデザインに対応させました。
/auth/loginにアクセスします
画面をちっちゃくしてみると、ハンバーガーメニューが登場したり、文言が省略されます
レスポンシブです。!
1. 〇〇の画面を開く
3. ...
> created responsive design

- app/features/game/core/objects/player.ts
ゲーム内のプレイヤーアイコン上に、idを表示するようにしました。
アイコンはなんかダメだったのであとでやります。
`/game` or `/debug` を開き、名前が表示されるか確認してください。
> プレイヤー名を表示してみた

- app/api/getUsers.server.ts
- app/api/startGame.client.ts
- app/atoms/githubUser.ts
- app/components/CreateRoomModal.tsx
- app/components/StartButton.tsx
- app/root.tsx
- app/routes/waiting.tsx
> 開始通知をブロードキャストする

- app/components/JoinRoomModal.tsx
- 参加ボタンを押してローディング中になることを確認
- モーダルを閉じるとローディングではなく参加するが表示される
> add: 参加ボタンのローディング実装

- app/components/CreateRoomModal.tsx
- app/components/JoinRoomModal.tsx
- 部屋作成モーダルにローディングアニメーション実装
- JoinRoomModalをバツボタンで閉じれるように修正
- 部屋作成ボタンを押したらローディング画面が表示される
- バリデーションに弾かれたらローディングが表示されないことを確認
- 参加モーダルがバツボタンで閉じられるか確認
> add: 部屋作成モーダルのローディング実装

- app/components/JoinRoomModal.tsx
- app/routes/waiting.tsx
- app/utils/calcStatus.ts
> status情報を計算

- app/atoms/socket.ts
- app/components/CreateRoomModal.tsx
- app/routes/waiting.tsx
> websocketをjotaiで保持

- app/api/sendAction.server.ts
- app/api/startGame.client.ts
- app/components/JoinRoomModal.tsx
> アクション送受信のクライアントを作成

- app/routes/result.tsx
- ライトモード、ダークモードの両方で/resultが正常に表示されるか確認
> fix: リザルト画面がダークモードでも正常に表示されるように修正

- app/routes/waiting.tsx
> fix: redirect 時に ws を切らないようにした

- app/features/game/components/PhaserGame.tsx
- app/features/game/core/objects/player.ts
- app/routes/waiting.tsx
> ゲーム終了時/破棄時にWebSocket connectをクローズするようにした

- app/components/StatusCard.tsx
- app/components/StatusChart.tsx
- app/features/game/components/PhaserGame.tsx
- app/features/game/core/config/configLoader.ts
- app/features/game/core/objects/player.ts
- app/routes/result.tsx
- app/routes/status.tsx
- app/routes/waiting.tsx
- app/utils/calcStatus.ts
> ステータスページを作成

- app/atoms/players.ts
- app/routes/game.tsx
- app/routes/waiting.tsx
> player data -> PhaserGame にいれた

- app/utils/calcStatus.ts
> cool downの閾値を修正

- app/features/game/core/config/configLoader.ts
> feat: ActionQueue を導入してみた

- app/components/StatusCard.tsx
- app/components/StatusChart.tsx
> fix: cdの閾値を修正

- app/components/StatusCard.tsx
> fix: rankの計算を修正

- app/features/game/core/config/configLoader.ts
- app/features/game/core/state/ClientGameStateManager.ts
- app/routes/result.tsx
> feat: カウントダウン実装

- app/components/CreateRoomModal.tsx
> fix: modalが先に消える問題を修正

- app/features/game/core/config/configLoader.ts
- app/features/game/core/objects/player.ts
> 衝突の大きさを大きくした

- app/components/StartButton.tsx
- app/routes/waiting.tsx
waitingのデザイン改善
1. 〇〇の画面を開く
3. ...
> update: waitingDesign
